@Library('shared-library')_
pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
            post{
                always{
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Delivery'){
            steps{
                echo "Delivery completed"
            }
        }
        stage('Shared library'){
            steps{
                hello 'Welcome to groovy'
            }
        }
    }
    post{
        success{
            slackSend channel: '#jenkinsci',
                      color: 'good',
                      message: "Executed the job ${currentBuild.fullDisplayName}"
        }
        failure{
            slackSend channel: '#jenkinsci',
                      color: 'danger',
                      message: "Failed to execute the job ${currentBuild.fullDisplayName}"
        }
    }
}