@Library('shared-library')_

import com.groovybuilder.globalvarClass
import com.groovybuilder.sampleClass

pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
            post{
                always{
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Delivery'){
            steps{
                echo "Delivery completed"
            }
        }
        stage('Shared library'){
            steps{
                hello 'Welcome to groovy'
                echo "The value of global variable foo is: " + globalvarClass.foo
                script{
                    def person = new sampleClass()
                    person.age = 29
                    person.incrementAge(10)
                    println "Incremented age is: "+person.age
                }
            }
        }
    }
    post{
        success{
            slackSend channel: '#jenkinsci',
                      color: 'good',
                      message: "Executed the job ${currentBuild.fullDisplayName}"
        }
        failure{
            slackSend channel: '#jenkinsci',
                      color: 'danger',
                      message: "Failed to execute the job ${currentBuild.fullDisplayName}"
        }
    }
}