pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                bat 'C:\Program Files\apache-maven-3.6.3-bin\apache-maven-3.6.3\bin\mvn -B -DskipTests clean package'
            }
        }
        stage('Test'){
            steps{
                bat 'mvn test'
            }
            post{
                always{
                    junut 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Delivery'){
            steps{
                echo "Delivery completed"
            }
        }
    }
}